### PR TITLE
Update github action packages

### PR DESCRIPTION
**Pull request by C10ne**
This pull request fixes the warning mentioned in issue #18 by updating versions of core github actions to their latest versions.

### CODE REVIEW

**Comment by benpickles** [comment]
It seems odd to include `node_modules/*` in this repo, is this normal for GitHub Actions?

Ah I see that the libs were previously referenced with `file:` - which suggests they can now be removed from the repo in this PR?

https://github.com/miloserdow/capistrano-deploy/blob/33558a5f4369a35901feab9180b6fd8af264ae7f/package.json#L8-L12

**Comment by C10ne** [comment]
I'm not sure why it's the preferred way for the author to include them, I prefer to have major versions in package.json. At the moment node_modules are included, it might be the way for actions to skip installation, might be the normal way for actions to handle requirements.
I've, kinda, made this PR just to point to the fix for the error, and have a replacement ready if the main repo is not updated in time.
It's up to author to decide how to move forward on the topic of requirements.

**Comment by miloserdow** [comment]
Hey, thanks for this pull request, it really saves the day!

@benpickles, fair point regarding node_modules issue. I created a tracker for it (#20). I have little JS experience, so probably there're more than one ways to improve this project :)

**Comment by felipecsl** [comment]
Any plans to push a new release with this change? :)

**Comment by miloserdow** [comment]
> Any plans to push a new release with this change? :) it's already nov 16th 😬

Done!

**Pull request merged**
